In [4]:
import numpy as np

# 1차원 배열
arr = np.array([1,2,3])
print(arr)
print()
# 2차원 배열
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [6]:
# list와 array
print("[1,2,3]의 type: ", type([1,2,3]))
print("arr의 type: ", type(arr))

[1,2,3]의 type:  <class 'list'>
arr의 type:  <class 'numpy.ndarray'>
