In [4]:
import numpy as np

# 1차원 배열
arr = np.array([1,2,3])
print(arr)
print()
# 2차원 배열
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [6]:
# list와 array
print("[1,2,3]의 type: ", type([1,2,3]))
print("arr의 type: ", type(arr))

[1,2,3]의 type:  <class 'list'>
arr의 type:  <class 'numpy.ndarray'>


In [10]:
# tuple array
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)
print()
# list array
lst = [1,2,3]
arr = np.array(lst)
print(arr)
print()
# list 2차원 array
lst2 = [[1,2,3], [4,5,6]]
arr = np.array(lst2)
print(arr)

[4 5 6]

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [12]:
# shape : array의 형태, 모양
arr1 = np.array([1,2,3])            # 원소가 3개인 1차원 array
arr2 = np.array([[1,2,3], [4,5,6]])   # 행이 2개이고, 열이 3개인 2차원 array

print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)
