In [5]:
import numpy as np

# 1차원 넘파이 배열을 생성하고 출력하면, 넘파이가 자동으로 이 배열의 데이터 형을 인식해서 정수형으로 출력해준다
# 데이터 형식을 지정하기 위해서는 array 함수의 인자로 dtype을 사용한다.
arr = np.array([1,2,3], dtype=np.float)     # 데이터가 실수형으로 출력된다.
# float64 : 해당 array에 각 성분을 표현할 때 메모리 상에 몇 bit를 사용할 것인지를 나타내는 수
print(arr, arr.dtype)

[1. 2. 3.] float64


C:\Users\easya\AppData\Local\Temp\ipykernel_2672\3414493499.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([1,2,3], dtype=np.float)     # 데이터가 실수형으로 출력된다.


In [6]:
# dtype : int
arr = np.array([1.1, 2.2, 3.3], dtype=np.int)   
print(arr, arr.dtype)

[1 2 3] int32


C:\Users\easya\AppData\Local\Temp\ipykernel_2672\249849904.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([1.1, 2.2, 3.3], dtype=np.int)


In [7]:
# dtype : boolean
arr = np.array([0, 1, 1], dtype=np.bool)   
print(arr, arr.dtype)

[False  True  True] bool


C:\Users\easya\AppData\Local\Temp\ipykernel_2672\3157341389.py:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([0, 1, 1], dtype=np.bool)


In [9]:
# 정수 배열을 실수 형태로 변경
arr = np.array([0,1,2,3])
print(arr, arr.dtype)

arr = arr.astype(np.float32)
print(arr, arr.dtype)

[0 1 2 3] int32
[0. 1. 2. 3.] float32


In [12]:
# 파이썬 리스트 형은 여러가지 type들을 담을 수 있다.
[1, 2, 3.4]

[1, 2, 3.4]

In [15]:
# numpy의 array는 단일 데이터 타입만 담을 수 있다. 
# 데이터 타입이 혼재하는 경우
arr = np.array([1,2, 3.4])
print(arr, arr.dtype)

# 문자열 > 유니코드 형식으로 변경
arr = np.array([1, 2, 3.4, "64"])
print(arr, arr.dtype)

# 데이터 타입이 혼재하는 경우 데이터 타입 변경
arr = np.array([1, 2, 3.4, "64"], dtype=int)
print(arr, arr.dtype)

[1.  2.  3.4] float64
['1' '2' '3.4' '64'] <U32
[ 1  2  3 64] int32


In [16]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4, "64 문자열"], dtype=int)
print(arr, arr.dtype)

ValueError: invalid literal for int() with base 10: '64 문자열'