In [1]:
import numpy as np

# np.zeros() : 모든 원소들이 0으로 된 배열을 생성
arr = np.zeros([2,2])  # 함수의 인자로는 shape를 입력
print(arr)

[[0. 0.]
 [0. 0.]]


In [2]:
# np.ones() : 모든 원소들이 1로 된 배열을 생성
arr = np.ones([3,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
# np.full() : 특정 원소로 채워진 shape의 array
arr =  np.full((2,3), 5)     # 함수의 인자는 shape, fill value를 지정
print(arr)

[[5 5 5]
 [5 5 5]]


In [4]:
# np.eye() : 행을 n, 열을 m이라고 했을 때 `n x m` shape을 가진 대각 원소가 1인 행렬 
arr = np.eye(3, 4, k=0)  # k는 대각원소의 발생지점을 지정
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [7]:
# np.eye() : 행을 n, 열을 m이라고 했을 때 `n x m` shape을 가진 대각 원소가 1인 행렬 
arr = np.eye(3, 4, k=0)  # k는 대각원소의 발생지점을 지정
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# np.eye() : 행을 n, 열을 m이라고 했을 때 `n x m` shape을 가진 대각 원소가 1인 행렬 
arr = np.eye(3, 4, k=-1)  # k는 대각원소의 발생지점을 지정
print(arr)

In [8]:
# np.eye() : 행을 n, 열을 m이라고 했을 때 `n x m` shape을 가진 대각 원소가 1인 행렬 
arr = np.eye(3) 
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
arr = np.array([[1,2,3], 
                [4,5,6]])

# np.zeros_like()
arr_z = np.zeros_like(arr)
print(arr_z)

[[0 0 0]
 [0 0 0]]


In [10]:
# np.ones_like()
arr_o = np.ones_like(arr)
print(arr_o)

[[1 1 1]
 [1 1 1]]


In [11]:
# np.full_like()
arr_f = np.full_like(arr, 9)
print(arr_f)

[[9 9 9]
 [9 9 9]]
