In [1]:
import numpy as np

# np.zeros() : 모든 원소들이 0으로 된 배열을 생성
arr = np.zeros([2,2])  # 함수의 인자로는 shape를 입력
print(arr)

[[0. 0.]
 [0. 0.]]


In [2]:
# np.ones() : 모든 원소들이 1로 된 배열을 생성
arr = np.ones([3,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
