In [1]:
lst = list(range(0,9,2))
print(lst)

[0, 2, 4, 6, 8]


In [6]:
import numpy as np

arr = np.arange(9)
print(arr)

arr = np.arange(3, 13)
print(arr)

arr = np.arange(3,13,3)
print(arr)

arr = np.arange(stop=9, step=2, start=0)    # (0,9,2)
print(arr)

[0 1 2 3 4 5 6 7 8]
[ 3  4  5  6  7  8  9 10 11 12]
[ 3  6  9 12]
[0 2 4 6 8]


In [8]:
# np.linspace()
arr = np.linspace(0,100, 11)    # 0부터 100까지 11개의 원소가 균등한 간격으로 출력
print(arr)

arr = np.linspace(0,100, 250)    
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[  0.           0.40160643   0.80321285   1.20481928   1.6064257
   2.00803213   2.40963855   2.81124498   3.21285141   3.61445783
   4.01606426   4.41767068   4.81927711   5.22088353   5.62248996
   6.02409639   6.42570281   6.82730924   7.22891566   7.63052209
   8.03212851   8.43373494   8.83534137   9.23694779   9.63855422
  10.04016064  10.44176707  10.84337349  11.24497992  11.64658635
  12.04819277  12.4497992   12.85140562  13.25301205  13.65461847
  14.0562249   14.45783133  14.85943775  15.26104418  15.6626506
  16.06425703  16.46586345  16.86746988  17.26907631  17.67068273
  18.07228916  18.47389558  18.87550201  19.27710843  19.67871486
  20.08032129  20.48192771  20.88353414  21.28514056  21.68674699
  22.08835341  22.48995984  22.89156627  23.29317269  23.69477912
  24.09638554  24.49799197  24.89959839  25.30120482  25.70281124
  26.10441767  26.5060241   26.90763052  27.30923695  27.71084337
  28.1124498   28.514