In [1]:
lst = list(range(0,9,2))
print(lst)

[0, 2, 4, 6, 8]


In [6]:
import numpy as np

arr = np.arange(9)
print(arr)

arr = np.arange(3, 13)
print(arr)

arr = np.arange(3,13,3)
print(arr)

arr = np.arange(stop=9, step=2, start=0)    # (0,9,2)
print(arr)

[0 1 2 3 4 5 6 7 8]
[ 3  4  5  6  7  8  9 10 11 12]
[ 3  6  9 12]
[0 2 4 6 8]


In [7]:
# np.linspace()
arr = np.linspace(0,100, 11)    # 0부터 100까지 11개의 원소가 균등한 간격으로 출력
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
