In [1]:
# 특정 인덱스를 여러 개 선택해서 탐색하는 방법
# 1 차원 배열
import numpy as np

arr = np.array([5,10,15,20,25,30])
print(arr[[0,2,4]])     # 0번째, 2번째, 4번째 원소를 가지고 오겠다는 의미

[ 5 15 25]


In [2]:
# 2차원 배열
arr = np.array([[5,10,15,20],
                [25,30,35,40],
                [45,50,55,60]])
print(arr[[0,2], 2:])
print(arr[1:, [2,3]])

[[15 20]
 [55 60]]
[[35 40]
 [55 60]]
