In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[2,2,2],
                [2,2,2],
                [2,2,2]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:
# 덧셈
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# 뺄셈
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [6]:
# 곱셈 : 원소끼리 곱셈 (dot product --> X)
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
# 나눗셈
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [10]:
# 제곱
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[2,2,2],
                [2,2,2],
                [2,2,2]])
print(arr1 ** 2)
print(np.square(arr1))  # 자기 자신을 제곱

# 제곱근
print(np.sqrt(arr1))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
