In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [0,1,4]])

In [3]:
# min()
print(np.min(arr))
print(arr.min())
print(arr.min(axis=0))

0
0
[0 1 3]


In [4]:
# max()
print(np.max(arr))
print(arr.max())
print(arr.max(axis=1))

4
4
[3 4]


In [5]:
# sum()
print(np.sum(arr))
print(arr.sum(axis=0))

11
[1 3 7]


In [6]:
# mean()
print(np.mean(arr))
print(arr.mean(axis=0))

1.8333333333333333
[0.5 1.5 3.5]


In [7]:
# std() : 표준편차
print(np.std(arr))
print(arr.std(axis=0))

1.343709624716425
[0.5 0.5 0.5]


In [8]:
# cumsum() : 누적값
print(np.cumsum(arr))
print(arr.cumsum())
print(arr.cumsum(axis=0))

[ 1  3  6  6  7 11]
[ 1  3  6  6  7 11]
[[1 2 3]
 [1 3 7]]


In [9]:
# median() : 중간에 있는 값, 짝수 개일 경우 가운데 두 숫자 사이의 중간값을 출력
print(np.median(arr))

1.5
