- 배열의 shape이 다를 경우의 연산

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[0,0,0],
                [1,1,1],
                [2,2,2]])
arr2 = np.array([[5,6,7]])

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
