In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10, size=10)
print(arr)

[1 4 7 7 3 4 7 7 0 3]


In [4]:
# sort : 오름차순 정렬
print(np.sort(arr))
print(np.sort(arr)[::-1])   # 내림차순 정렬

[0 1 3 3 4 4 7 7 7 7]
[7 7 7 7 4 4 3 3 1 0]


In [6]:
print(arr)  # 정렬되지 않은 형태
arr = np.sort(arr)  # 정렬된 형태의 배열을 정의

[1 4 7 7 3 4 7 7 0 3]


In [7]:
arr.sort()
print(arr)

[0 1 3 3 4 4 7 7 7 7]
