In [1]:
import numpy as np

In [3]:
arr = np.random.randint(15, size=(3,4))
print(arr)

[[14  9  8 13]
 [ 5 11  7  2]
 [ 5  8  8  4]]


In [4]:
# x축 기준 정렬
print(np.sort(arr, axis=0))

[[ 5  8  7  2]
 [ 5  9  8  4]
 [14 11  8 13]]


In [5]:
# 2차원 배열을 1차원 배열로 변경
print(np.sort(arr, axis=None))

[ 2  4  5  5  7  8  8  8  9 11 13 14]
