In [1]:
import numpy as np

In [6]:
arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3,4))
print(arr, arr.ndim)

arr = arr.reshape((2,3,2))
print(arr, arr.ndim)

arr = arr.reshape((2,2,1,3))
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4
