In [1]:
import numpy as np

In [6]:
arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3,4))
print(arr, arr.ndim)

arr = arr.reshape((2,3,2))
print(arr, arr.ndim)

arr = arr.reshape((2,2,1,3))
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


- Curse Of Dimensionality (차원의 저주)
    - 빅데이터, 딥러닝시
    - 차원이 증가하면서 학습 데이터 수가 차원의 수보다 적어지면서, 모델의 성능이 저하되는 현상
    - 좌표 상에서, 데이터 수가 10개로 일정하다고 할 때,
        - 직선이라면 데이터 상의 거리가 거의 균등
        - 2차원일 경우 거리가 1차원보다 멀어짐