In [1]:
import numpy as np

In [2]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# resize()
arr.resize(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
# ravel
arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
arr = np.arange(1, 13)
print(arr)

arr = arr.reshape(3, -1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
